name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build frontend
        run: |
          cd frontend
          npm install
          CI=false npm run build  #Warnings are ignored / If you want to deploy Frontend without any warnings (HIGHLY RECOMMENDED!), remove "CI=flase" 
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: template.jar #Must be the same as 'finalName' in pom.xml
          path: backend/target/template.jar

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment: #optional, zeigt 'nur' den Link im Repo an
      name: template-heroku
      url: https://kevinowens.herokuapp.com/ #change to your App-URL provided by heroku
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: template.jar  #Must be the same as 'finalName' in pom.xml
          path: backend/target
      - name: Login to heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a kevinowens #Change with your heroku-app name
      - name: Deploy docker container
        run: heroku container:release web -a kevinowens #Change with your heroku-app name
